#!/usr/bin/env python3
"""
Generates the 404 artwork in both places it has to exist.

The standalone page (web/public/404.html) must render with the application
down — a reverse proxy serves it on its own — so it cannot import anything from
the bundle. The in-app screen (web/src/components/NotFound.tsx) is React. Two
copies of one drawing is a smell, so neither is written by hand: both come from
here, and the stylesheet they share lives once in web/src/styles.css under the
`.g404` prefix.

    python3 scripts/mk404.py

Run it after changing the gear layout or the copy on the standalone page.
"""

from pathlib import Path
import math, re, sys
sys.path.insert(0, str(Path(__file__).parent))
from _gears import GEARS

# Every spinning shape is wrapped in a <g> that carries the placement, and the
# rotation is animated on the child. A CSS `transform` REPLACES an SVG
# `transform` attribute rather than composing with it, so animating the same
# element that carries translate() throws the shape into the top-left corner.
def cog(kind, colour, x, y, scale=1.0, spin="", extra=""):
    s = f" scale({scale})" if scale != 1.0 else ""
    return (f'<g transform="translate({x} {y}){s}">'
            f'<path class="c c--{colour} sp{spin}" d="{GEARS[kind]}"{extra}/></g>')

def spokes(r, step=15):
    out = []
    for a in range(0, 360, step):
        out.append(f'<line x1="0" y1="0" x2="{r*math.cos(math.radians(a)):.1f}" y2="{r*math.sin(math.radians(a)):.1f}"/>')
    return "".join(out)

CX, CY, R = 185, 332, 126

CLUSTER = f'''<svg class="g404__art" viewBox="0 0 540 540" role="img" aria-labelledby="g404-art-title">
      <title id="g404-art-title">Сцепленные шестерни</title>

      <!-- Ghosts behind everything, only to give the pile some depth. -->
      <g class="g404__ghost">
        <g transform="translate(345 205) scale(1.3)"><path class="sp sp--slow" d="{GEARS['big']}"/></g>
        <g transform="translate(160 415) scale(1.35)"><path class="sp sp--rev" d="{GEARS['mid']}"/></g>
      </g>

      <!-- The wheel: the one round thing among the cogs, and the reason the
           cluster reads as a machine rather than a heap of stars. -->
      <g class="g404__wheel" transform="translate({CX} {CY})">
        <circle class="rim" r="{R}"/>
        <g class="spokes">{spokes(R - 5)}</g>
        <circle class="hub" r="26"/>
      </g>

      <!-- Foreground cogs. Meshing neighbours turn opposite ways: that contrast
           is what sells the mechanism; all-same-direction reads as a slideshow. -->
      {cog('mid',   'dark', 222, 116, spin=' sp--slow')}
      {cog('small', 'teal', 222, 116, 0.6, ' sp--rev')}

      {cog('big',   'teal', 330, 248)}
      {cog('small', 'lime', 330, 248, 0.78, ' sp--rev')}

      {cog('mid',   'dark', 452, 336, spin=' sp--rev')}
      {cog('tiny',  'teal', 452, 336, 0.72)}

      {cog('small', 'lime', 338, 430)}
      {cog('tiny',  'dark', 338, 430, 0.9, ' sp--rev')}

      <!-- The loose cog on a plumb line: the one part driving nothing, which is
           rather the point of an error page. -->
      <g class="g404__loose">
        <circle class="dash" cx="104" cy="112" r="70"/>
        {cog('small', 'teal', 104, 112, 0.84, ' sp--slow')}
        <line class="plumb" x1="104" y1="182" x2="104" y2="466"/>
        <rect class="weight" x="92" y="466" width="24" height="40" rx="4"/>
        <rect class="weight" x="97" y="456" width="14" height="12" rx="3"/>
      </g>
    </svg>'''

# ---------------------------------------------------------------- outputs

root = Path(__file__).resolve().parent.parent
css_src = (root / "web/src/styles.css").read_text(encoding="utf-8")

# Lift the shared block straight out of the stylesheet, so the standalone page
# can never disagree with the in-app screen about colour or motion.
start = css_src.index(".g404 {")
end = css_src.index("/* --------------------------------------------------------- narrow screens */")
shared_css = css_src[start:end].rstrip()
# The grid-column line only means something inside the app shell.
shared_css = shared_css.replace(
    "  /* The app shell is a grid; the error screen takes the whole width of it. */\n"
    "  grid-column: 1 / -1;\n", "")

html = f"""<!doctype html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex" />
    <title>404 — страница не найдена · Kivora</title>
    <!-- GENERATED by scripts/mk404.py — edit that, not this.
         Standalone on purpose: no script, no webfont, no image file, nothing
         fetched. This page has to render when the application it belongs to is
         the very thing that is down. -->
    <style>
      * {{ box-sizing: border-box; }}
      html, body {{ margin: 0; padding: 0; background: #0d4b50; }}
{shared_css}
    </style>
  </head>
  <body>
    <main class="g404">
      {CLUSTER}

      <div class="g404__text">
        <p class="g404__code">Ошибка 404</p>
        <h1 class="g404__title">Такой страницы здесь нет</h1>
        <p class="g404__lead">
          Механизм на месте и крутится — просто эта ссылка ни к чему не
          подключена. Возможно, чат удалили или адрес набран с ошибкой.
        </p>
        <div class="g404__actions">
          <a class="g404__btn" href="/">Вернуться к чатам</a>
          <a class="g404__btn g404__btn--ghost" href="javascript:history.back()">Назад</a>
        </div>
        <p class="g404__foot">Kivora — мессенджер со сквозным шифрованием</p>
      </div>
    </main>
  </body>
</html>
"""
(root / "web/public/404.html").write_text(html, encoding="utf-8")

# The React copy: same drawing, translated strings, buttons that route in-app.
jsx = CLUSTER.replace("class=", "className=").replace("stroke-width=", "strokeWidth=")
jsx = re.sub(r"<!--(.*?)-->", lambda m: "{/*" + m.group(1) + "*/}", jsx, flags=re.S)
jsx = "\n".join(("      " + ln) if ln.strip() else ln for ln in jsx.split("\n"))

component = '''import { useSession } from "../state/useSession.ts";
import { useT } from "../i18n/useT.ts";

/**
 * The 404 screen. GENERATED by scripts/mk404.py — edit that, not this.
 *
 * Shares its drawing and its stylesheet (`.g404` in styles.css) with
 * web/public/404.html, which has to survive with the app down and therefore
 * cannot import from the bundle.
 *
 * Everything moves in CSS: no canvas, no animation library, nothing holding a
 * timer — a hidden tab pauses CSS animations on its own.
 */
export function NotFound() {
  const session = useSession();
  const { t } = useT();

  return (
    <main className="g404">
%s

      <div className="g404__text">
        <p className="g404__code">{t("notFound.code")}</p>
        <h1 className="g404__title">{t("notFound.title")}</h1>
        <p className="g404__lead">{t("notFound.text")}</p>
        <div className="g404__actions">
          <button className="g404__btn" onClick={() => session.goHome()}>
            {t("notFound.home")}
          </button>
          <button className="g404__btn g404__btn--ghost" onClick={() => window.history.back()}>
            {t("common.back")}
          </button>
        </div>
        <p className="g404__foot">{t("app.tagline")}</p>
      </div>
    </main>
  );
}
''' % jsx
(root / "web/src/components/NotFound.tsx").write_text(component, encoding="utf-8")

print("wrote web/public/404.html and web/src/components/NotFound.tsx")
