import { useSession } from "../state/useSession.ts";
import { useT } from "../i18n/useT.ts";

/**
 * The 404 screen. GENERATED by scripts/mk404.py — edit that, not this.
 *
 * Shares its drawing and its stylesheet (`.g404` in styles.css) with
 * web/public/404.html, which has to survive with the app down and therefore
 * cannot import from the bundle.
 *
 * Everything moves in CSS: no canvas, no animation library, nothing holding a
 * timer — a hidden tab pauses CSS animations on its own.
 */
export function NotFound() {
  const session = useSession();
  const { t } = useT();

  return (
    <main className="g404">
      <svg className="g404__art" viewBox="0 0 540 540" role="img" aria-labelledby="g404-art-title">
            <title id="g404-art-title">Сцепленные шестерни</title>

            {/* Ghosts behind everything, only to give the pile some depth. */}
            <g className="g404__ghost">
              <g transform="translate(345 205) scale(1.3)"><path className="sp sp--slow" d="M76.7 -14.3 L99.4 -11.0 L99.4 11.0 L76.7 14.3 L73.6 25.9 L91.6 40.2 L80.6 59.2 L59.2 50.8 L50.8 59.2 L59.2 80.6 L40.2 91.6 L25.9 73.6 L14.3 76.7 L11.0 99.4 L-11.0 99.4 L-14.3 76.7 L-25.9 73.6 L-40.2 91.6 L-59.2 80.6 L-50.8 59.2 L-59.2 50.8 L-80.6 59.2 L-91.6 40.2 L-73.6 25.9 L-76.7 14.3 L-99.4 11.0 L-99.4 -11.0 L-76.7 -14.3 L-73.6 -25.9 L-91.6 -40.2 L-80.6 -59.2 L-59.2 -50.8 L-50.8 -59.2 L-59.2 -80.6 L-40.2 -91.6 L-25.9 -73.6 L-14.3 -76.7 L-11.0 -99.4 L11.0 -99.4 L14.3 -76.7 L25.9 -73.6 L40.2 -91.6 L59.2 -80.6 L50.8 -59.2 L59.2 -50.8 L80.6 -59.2 L91.6 -40.2 L73.6 -25.9 Z M30.0 0 A30.0 30.0 0 1 0 -30.0 0 A30.0 30.0 0 1 0 30.0 0 Z"/></g>
              <g transform="translate(160 415) scale(1.35)"><path className="sp sp--rev" d="M49.8 -11.2 L65.4 -8.7 L65.4 8.7 L49.8 11.2 L46.8 20.2 L58.0 31.4 L47.8 45.5 L33.7 38.3 L26.0 43.8 L28.5 59.5 L12.0 64.9 L4.7 50.8 L-4.7 50.8 L-12.0 64.9 L-28.5 59.5 L-26.0 43.8 L-33.7 38.3 L-47.8 45.5 L-58.0 31.4 L-46.8 20.2 L-49.8 11.2 L-65.4 8.7 L-65.4 -8.7 L-49.8 -11.2 L-46.8 -20.2 L-58.0 -31.4 L-47.8 -45.5 L-33.7 -38.3 L-26.0 -43.8 L-28.5 -59.5 L-12.0 -64.9 L-4.7 -50.8 L4.7 -50.8 L12.0 -64.9 L28.5 -59.5 L26.0 -43.8 L33.7 -38.3 L47.8 -45.5 L58.0 -31.4 L46.8 -20.2 Z M20.0 0 A20.0 20.0 0 1 0 -20.0 0 A20.0 20.0 0 1 0 20.0 0 Z"/></g>
            </g>

            {/* The wheel: the one round thing among the cogs, and the reason the
                 cluster reads as a machine rather than a heap of stars. */}
            <g className="g404__wheel" transform="translate(185 332)">
              <circle className="rim" r="126"/>
              <g className="spokes"><line x1="0" y1="0" x2="121.0" y2="0.0"/><line x1="0" y1="0" x2="116.9" y2="31.3"/><line x1="0" y1="0" x2="104.8" y2="60.5"/><line x1="0" y1="0" x2="85.6" y2="85.6"/><line x1="0" y1="0" x2="60.5" y2="104.8"/><line x1="0" y1="0" x2="31.3" y2="116.9"/><line x1="0" y1="0" x2="0.0" y2="121.0"/><line x1="0" y1="0" x2="-31.3" y2="116.9"/><line x1="0" y1="0" x2="-60.5" y2="104.8"/><line x1="0" y1="0" x2="-85.6" y2="85.6"/><line x1="0" y1="0" x2="-104.8" y2="60.5"/><line x1="0" y1="0" x2="-116.9" y2="31.3"/><line x1="0" y1="0" x2="-121.0" y2="0.0"/><line x1="0" y1="0" x2="-116.9" y2="-31.3"/><line x1="0" y1="0" x2="-104.8" y2="-60.5"/><line x1="0" y1="0" x2="-85.6" y2="-85.6"/><line x1="0" y1="0" x2="-60.5" y2="-104.8"/><line x1="0" y1="0" x2="-31.3" y2="-116.9"/><line x1="0" y1="0" x2="-0.0" y2="-121.0"/><line x1="0" y1="0" x2="31.3" y2="-116.9"/><line x1="0" y1="0" x2="60.5" y2="-104.8"/><line x1="0" y1="0" x2="85.6" y2="-85.6"/><line x1="0" y1="0" x2="104.8" y2="-60.5"/><line x1="0" y1="0" x2="116.9" y2="-31.3"/></g>
              <circle className="hub" r="26"/>
            </g>

            {/* Foreground cogs. Meshing neighbours turn opposite ways: that contrast
                 is what sells the mechanism; all-same-direction reads as a slideshow. */}
            <g transform="translate(222 116)"><path className="c c--dark sp sp--slow" d="M49.8 -11.2 L65.4 -8.7 L65.4 8.7 L49.8 11.2 L46.8 20.2 L58.0 31.4 L47.8 45.5 L33.7 38.3 L26.0 43.8 L28.5 59.5 L12.0 64.9 L4.7 50.8 L-4.7 50.8 L-12.0 64.9 L-28.5 59.5 L-26.0 43.8 L-33.7 38.3 L-47.8 45.5 L-58.0 31.4 L-46.8 20.2 L-49.8 11.2 L-65.4 8.7 L-65.4 -8.7 L-49.8 -11.2 L-46.8 -20.2 L-58.0 -31.4 L-47.8 -45.5 L-33.7 -38.3 L-26.0 -43.8 L-28.5 -59.5 L-12.0 -64.9 L-4.7 -50.8 L4.7 -50.8 L12.0 -64.9 L28.5 -59.5 L26.0 -43.8 L33.7 -38.3 L47.8 -45.5 L58.0 -31.4 L46.8 -20.2 Z M20.0 0 A20.0 20.0 0 1 0 -20.0 0 A20.0 20.0 0 1 0 20.0 0 Z"/></g>
            <g transform="translate(222 116) scale(0.6)"><path className="c c--teal sp sp--rev" d="M32.7 -9.3 L43.4 -7.2 L43.4 7.2 L32.7 9.3 L29.7 16.5 L35.8 25.6 L25.6 35.8 L16.5 29.7 L9.3 32.7 L7.2 43.4 L-7.2 43.4 L-9.3 32.7 L-16.5 29.7 L-25.6 35.8 L-35.8 25.6 L-29.7 16.5 L-32.7 9.3 L-43.4 7.2 L-43.4 -7.2 L-32.7 -9.3 L-29.7 -16.5 L-35.8 -25.6 L-25.6 -35.8 L-16.5 -29.7 L-9.3 -32.7 L-7.2 -43.4 L7.2 -43.4 L9.3 -32.7 L16.5 -29.7 L25.6 -35.8 L35.8 -25.6 L29.7 -16.5 Z M13.0 0 A13.0 13.0 0 1 0 -13.0 0 A13.0 13.0 0 1 0 13.0 0 Z"/></g>

            <g transform="translate(330 248)"><path className="c c--teal sp" d="M76.7 -14.3 L99.4 -11.0 L99.4 11.0 L76.7 14.3 L73.6 25.9 L91.6 40.2 L80.6 59.2 L59.2 50.8 L50.8 59.2 L59.2 80.6 L40.2 91.6 L25.9 73.6 L14.3 76.7 L11.0 99.4 L-11.0 99.4 L-14.3 76.7 L-25.9 73.6 L-40.2 91.6 L-59.2 80.6 L-50.8 59.2 L-59.2 50.8 L-80.6 59.2 L-91.6 40.2 L-73.6 25.9 L-76.7 14.3 L-99.4 11.0 L-99.4 -11.0 L-76.7 -14.3 L-73.6 -25.9 L-91.6 -40.2 L-80.6 -59.2 L-59.2 -50.8 L-50.8 -59.2 L-59.2 -80.6 L-40.2 -91.6 L-25.9 -73.6 L-14.3 -76.7 L-11.0 -99.4 L11.0 -99.4 L14.3 -76.7 L25.9 -73.6 L40.2 -91.6 L59.2 -80.6 L50.8 -59.2 L59.2 -50.8 L80.6 -59.2 L91.6 -40.2 L73.6 -25.9 Z M30.0 0 A30.0 30.0 0 1 0 -30.0 0 A30.0 30.0 0 1 0 30.0 0 Z"/></g>
            <g transform="translate(330 248) scale(0.78)"><path className="c c--lime sp sp--rev" d="M32.7 -9.3 L43.4 -7.2 L43.4 7.2 L32.7 9.3 L29.7 16.5 L35.8 25.6 L25.6 35.8 L16.5 29.7 L9.3 32.7 L7.2 43.4 L-7.2 43.4 L-9.3 32.7 L-16.5 29.7 L-25.6 35.8 L-35.8 25.6 L-29.7 16.5 L-32.7 9.3 L-43.4 7.2 L-43.4 -7.2 L-32.7 -9.3 L-29.7 -16.5 L-35.8 -25.6 L-25.6 -35.8 L-16.5 -29.7 L-9.3 -32.7 L-7.2 -43.4 L7.2 -43.4 L9.3 -32.7 L16.5 -29.7 L25.6 -35.8 L35.8 -25.6 L29.7 -16.5 Z M13.0 0 A13.0 13.0 0 1 0 -13.0 0 A13.0 13.0 0 1 0 13.0 0 Z"/></g>

            <g transform="translate(452 336)"><path className="c c--dark sp sp--rev" d="M49.8 -11.2 L65.4 -8.7 L65.4 8.7 L49.8 11.2 L46.8 20.2 L58.0 31.4 L47.8 45.5 L33.7 38.3 L26.0 43.8 L28.5 59.5 L12.0 64.9 L4.7 50.8 L-4.7 50.8 L-12.0 64.9 L-28.5 59.5 L-26.0 43.8 L-33.7 38.3 L-47.8 45.5 L-58.0 31.4 L-46.8 20.2 L-49.8 11.2 L-65.4 8.7 L-65.4 -8.7 L-49.8 -11.2 L-46.8 -20.2 L-58.0 -31.4 L-47.8 -45.5 L-33.7 -38.3 L-26.0 -43.8 L-28.5 -59.5 L-12.0 -64.9 L-4.7 -50.8 L4.7 -50.8 L12.0 -64.9 L28.5 -59.5 L26.0 -43.8 L33.7 -38.3 L47.8 -45.5 L58.0 -31.4 L46.8 -20.2 Z M20.0 0 A20.0 20.0 0 1 0 -20.0 0 A20.0 20.0 0 1 0 20.0 0 Z"/></g>
            <g transform="translate(452 336) scale(0.72)"><path className="c c--teal sp" d="M22.8 -7.5 L31.4 -6.0 L31.4 6.0 L22.8 7.5 L20.1 13.2 L24.3 20.8 L14.9 28.3 L8.4 22.5 L2.2 23.9 L-1.1 32.0 L-12.8 29.3 L-12.4 20.6 L-17.3 16.6 L-25.7 19.0 L-30.9 8.2 L-23.8 3.2 L-23.8 -3.2 L-30.9 -8.2 L-25.7 -19.0 L-17.3 -16.6 L-12.4 -20.6 L-12.8 -29.3 L-1.1 -32.0 L2.2 -23.9 L8.4 -22.5 L14.9 -28.3 L24.3 -20.8 L20.1 -13.2 Z M10.0 0 A10.0 10.0 0 1 0 -10.0 0 A10.0 10.0 0 1 0 10.0 0 Z"/></g>

            <g transform="translate(338 430)"><path className="c c--lime sp" d="M32.7 -9.3 L43.4 -7.2 L43.4 7.2 L32.7 9.3 L29.7 16.5 L35.8 25.6 L25.6 35.8 L16.5 29.7 L9.3 32.7 L7.2 43.4 L-7.2 43.4 L-9.3 32.7 L-16.5 29.7 L-25.6 35.8 L-35.8 25.6 L-29.7 16.5 L-32.7 9.3 L-43.4 7.2 L-43.4 -7.2 L-32.7 -9.3 L-29.7 -16.5 L-35.8 -25.6 L-25.6 -35.8 L-16.5 -29.7 L-9.3 -32.7 L-7.2 -43.4 L7.2 -43.4 L9.3 -32.7 L16.5 -29.7 L25.6 -35.8 L35.8 -25.6 L29.7 -16.5 Z M13.0 0 A13.0 13.0 0 1 0 -13.0 0 A13.0 13.0 0 1 0 13.0 0 Z"/></g>
            <g transform="translate(338 430) scale(0.9)"><path className="c c--dark sp sp--rev" d="M22.8 -7.5 L31.4 -6.0 L31.4 6.0 L22.8 7.5 L20.1 13.2 L24.3 20.8 L14.9 28.3 L8.4 22.5 L2.2 23.9 L-1.1 32.0 L-12.8 29.3 L-12.4 20.6 L-17.3 16.6 L-25.7 19.0 L-30.9 8.2 L-23.8 3.2 L-23.8 -3.2 L-30.9 -8.2 L-25.7 -19.0 L-17.3 -16.6 L-12.4 -20.6 L-12.8 -29.3 L-1.1 -32.0 L2.2 -23.9 L8.4 -22.5 L14.9 -28.3 L24.3 -20.8 L20.1 -13.2 Z M10.0 0 A10.0 10.0 0 1 0 -10.0 0 A10.0 10.0 0 1 0 10.0 0 Z"/></g>

            {/* The loose cog on a plumb line: the one part driving nothing, which is
                 rather the point of an error page. */}
            <g className="g404__loose">
              <circle className="dash" cx="104" cy="112" r="70"/>
              <g transform="translate(104 112) scale(0.84)"><path className="c c--teal sp sp--slow" d="M32.7 -9.3 L43.4 -7.2 L43.4 7.2 L32.7 9.3 L29.7 16.5 L35.8 25.6 L25.6 35.8 L16.5 29.7 L9.3 32.7 L7.2 43.4 L-7.2 43.4 L-9.3 32.7 L-16.5 29.7 L-25.6 35.8 L-35.8 25.6 L-29.7 16.5 L-32.7 9.3 L-43.4 7.2 L-43.4 -7.2 L-32.7 -9.3 L-29.7 -16.5 L-35.8 -25.6 L-25.6 -35.8 L-16.5 -29.7 L-9.3 -32.7 L-7.2 -43.4 L7.2 -43.4 L9.3 -32.7 L16.5 -29.7 L25.6 -35.8 L35.8 -25.6 L29.7 -16.5 Z M13.0 0 A13.0 13.0 0 1 0 -13.0 0 A13.0 13.0 0 1 0 13.0 0 Z"/></g>
              <line className="plumb" x1="104" y1="182" x2="104" y2="466"/>
              <rect className="weight" x="92" y="466" width="24" height="40" rx="4"/>
              <rect className="weight" x="97" y="456" width="14" height="12" rx="3"/>
            </g>
          </svg>

      <div className="g404__text">
        <p className="g404__code">{t("notFound.code")}</p>
        <h1 className="g404__title">{t("notFound.title")}</h1>
        <p className="g404__lead">{t("notFound.text")}</p>
        <div className="g404__actions">
          <button className="g404__btn" onClick={() => session.goHome()}>
            {t("notFound.home")}
          </button>
          <button className="g404__btn g404__btn--ghost" onClick={() => window.history.back()}>
            {t("common.back")}
          </button>
        </div>
        <p className="g404__foot">{t("app.tagline")}</p>
      </div>
    </main>
  );
}
